extern crate alloc;

/// This module is auto-generated by the `raves_metadata_types` crate.
///
/// Please don't hand-edit. Instead, modify the code generation in `build.rs`.
pub mod iptc {
    include!(concat!(env!("OUT_DIR"), "/iptc_keys.rs"));
}

pub mod exif;
pub mod xmp;
