name: CI
on:
  - push
  - pull_request
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4

      - name: Cache Rust workspace build
        uses: Swatinem/rust-cache@98c8021b550208e191a6a3145459bfc9fb29c4c0

      - name: Update Rust
        run: rustup update stable

      - name: Install `cargo-binstall`
        run: curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash

      - name: Install `cargo-nextest`
        run: cargo binstall --no-confirm --force cargo-nextest

      - name: Install `cargo-semver-checks`
        run: cargo binstall --no-confirm --force cargo-semver-checks

      - name: Lint the project
        run: cargo clippy -- -A unused_variables

      - name: Run tests
        run: cargo nextest run --no-fail-fast

      - name: Check semantic versioning
        run: cargo semver-checks
